name: Rust CI Suite

on:
  [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clippy:
    if: github.event.pull_request.draft == false
    name: Cargo Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add clippy
      - uses: actions/checkout@v3
      - run: cargo clippy --workspace --tests -- -D warnings

  fmt:
    if: github.event.pull_request.draft == false
    name: Ensure rustfmt Standard
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: rustup component add rustfmt
      - uses: actions/checkout@v3
      - run: cargo fmt --all --verbose
