name: Rust CI Suite

on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Dependencies
      run: cargo build --locked

    - name: Run Clippy
      run: cargo clippy --all --all-targets --all-features -- -D warnings

    - name: Format Code
      run: cargo fmt --all -- --check

    - name: Run Tests
      run: cargo test --all --locked

    - name: Generate Code Coverage
      run: |
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)

    - name: Check Code Coverage
      run: cargo tarpaulin --all --locked --exclude-files "tests/**"
